"use client"
import { Toaster } from "@/components/ui/sonner";
import Header from "./_components/Header";
import "./globals.css";
import { Outfit } from "next/font/google"
import { usePathname } from "next/navigation";
import { UpdateCartContext } from "./_context/UpdateCart";
import { useState } from "react";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";

const outfit = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Grocery App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params = usePathname();
  const showHeader = params == '/sign-in' || params == "/create-account" ? false : true;
  const [updateCart, setUpdateCart] = useState(false);
  return (
    <PayPalScriptProvider options={{ clientId: process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID }}>

      <html lang="en">
        <body
          className={outfit.className}
        >
          <UpdateCartContext.Provider value={{ updateCart, setUpdateCart }}>

            {showHeader && <Header />}
            {children}
          </UpdateCartContext.Provider>
          <Toaster />
        </body>
      </html>
    </PayPalScriptProvider>
  );
}
